Post tags
StreetOfCode/streetofcode-web pull request #42
Opened 2023-03-07 19:38 UTC by xjahic

2023-03-08 13:14 UTC, xjahic commented on src/components/domain/buttons/Tag.tsx
> +const Tag = ({
Maybe rename to PostTag? And I should add a description as well

2023-03-09 14:58 UTC, gabrielKerekes requested changes
In general looks good, nice :+1: But please see comments on possible improvements/bug fixes.

2023-03-09 14:58 UTC, gabrielKerekes commented on src/wp/api.ts
> +          tags {
What do you think of doing something like [this](https://github.com/StreetOfCode/streetofcode-web/commit/d3081f4fb3bdfcc8d711569b1a210b3c9eba7d4b) so the schema wouldn't need to be duplicated?

2023-03-09 14:58 UTC, gabrielKerekes commented on src/utils.tsx
> +  const hey = tag
Wouldn't [encodeUriComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) and `replaceAll` do the job? What is the magic with normalize and special chars replace? If we have to keep it then a comment explaining it a little would be nice.

2023-03-09 14:58 UTC, gabrielKerekes commented on src/utils.tsx
> +  assert(!!tag, 'Článok nemá požadovaný tag')
Should this be here?

2023-03-09 14:58 UTC, gabrielKerekes commented on src/pages/clanky/[slug].tsx
> +    const posts = await getPostsByTag(
Isn't this a bit too expensive? For each post we'd do at least `RECOMMENDED_POSTS_NUMBER` requests which might be a pain at build time. And unnecessary. ... but I have no other, simple solution :D So I guess let's keep it. It's only done for articles so it should be fine.

2023-03-09 14:58 UTC, gabrielKerekes commented on src/components/domain/post/blog/clanky-constants.ts
> +export const RECOMMENDED_POSTS_NUMBER = 5
```suggestion
export const RECOMMENDED_POSTS_COUNT = 5
```

Oh and perhaps we could change it either into 3 or 6 so that they are nicely aligned. I think 3 should be enough, but I'm good with 6 as well.

2023-03-09 14:58 UTC, gabrielKerekes commented on src/components/domain/post/blog/TagBlogPosts.tsx
> +  tag = getTagFromUrlParam(tag, posts[0])
Can't this happen already in the `getServerSideProps`? And perhaps we could take this a bit further to simplify readability and create a `Tag` type which would have e.g. `raw` and `urlEncoded` props and this is what would get passed around. That way you don't have to think about whether the tag string you're currently working with is url encoded or not :shrug: And then in `getServerSideProps` you create this object, pass it to `PostsByTagPage` which in the `Head` `description` can display the `raw` tag and in `url` it can display the `urlEncoded` tag without much problems. And perhaps we wouldn't need `getTagFromUrlParam` at all.

2023-03-09 14:58 UTC, gabrielKerekes commented on src/components/domain/post/AuthorAndDate.tsx
> +  const handleOnClick = (e: React.MouseEvent) => {
Why is this required/better than a `Link`?

2023-03-09 14:58 UTC, gabrielKerekes commented on src/components/domain/buttons/Tag.tsx
> +const Tag = ({
`PostTag` is better.

2023-03-09 14:58 UTC, gabrielKerekes commented on src/components/domain/buttons/Tag.tsx
> +
I'd consider adding a `opacity: ${(props) => props.size === 'small' && '0.6'};` here - IMO the tags are a bit too visible given how (IMO) unimportant they are.

2023-03-09 14:58 UTC, gabrielKerekes commented on src/components/domain/post/RecommendedPostPreview.tsx
> +const RecommendedPostPreview = ({post, isPodcast}: Props) => {
Nice copy/paste :smile:

2023-03-09 14:58 UTC, gabrielKerekes commented on src/pages/clanky/[slug].tsx
> +  const recommendedPosts: Post[] = []
Posts can be duplicated, this should probably be built up as a map and then converted to a list.

Screenshot is from http://localhost:3000/clanky/ako-sa-naucit-programovat.
![image](https://user-images.githubusercontent.com/7520735/224062240-1120acee-2826-4842-ad75-6fe6ffe2abb6.png)

2023-03-09 14:58 UTC, gabrielKerekes commented on src/pages/clanky/[slug].tsx
> +  const recommendedPosts: Post[] = []
And we should probably revisit this at somepoint because currently some articles have a high chance of popping up while others might never show up here. Perhaps some shuffling of the tags and posts could be done? But then it wouldn't be deterministic :( :shrug: But this is ok for now.

2023-03-10 16:22 UTC, xjahic commented on src/pages/clanky/[slug].tsx
> +    const posts = await getPostsByTag(
That's not true. We don't have to do at least `RECOMMENDED_POSTS_NUMBER` requests. Number of requests is <1, post.tags.length>. 
It will be done for each article and each podcast. We can maybe find some optimization if it turns out to be a problem.

2023-03-10 16:23 UTC, xjahic commented on src/utils.tsx
> +  const hey = tag
I have tried it and `encodeURIComponent` did not remove diacritics. I have added a comment to this function.

2023-03-10 16:25 UTC, xjahic commented on src/components/domain/post/blog/clanky-constants.ts
> +export const RECOMMENDED_POSTS_NUMBER = 5
I'll change it to 3 so it looks better and also number of requests will be lower in average for each post.

2023-03-10 16:26 UTC, xjahic commented on src/components/domain/post/AuthorAndDate.tsx
> +  const handleOnClick = (e: React.MouseEvent) => {
Discussed offline. Reverted and fixed in different way

2023-03-10 16:27 UTC, xjahic commented on src/components/domain/buttons/Tag.tsx
> +
Agreed

2023-03-10 18:48 UTC, xjahic commented on src/pages/clanky/[slug].tsx
> +  const recommendedPosts: Post[] = []
Nice thanks. I fixed it and added some randomization.

2023-03-10 20:50 UTC, gabrielKerekes commented on src/pages/clanky/[slug].tsx
> +  const recommendedPosts: Post[] = []
Cool, much better with the randomization 👍

2023-03-10 20:54 UTC, gabrielKerekes commented on src/pages/clanky/[slug].tsx
> +    const posts = await getPostsByTag(
I see, my bad.

2023-03-11 13:32 UTC, xjahic commented on src/components/domain/post/blog/TagBlogPosts.tsx
> +  tag = getTagFromUrlParam(tag, posts[0])
Nice

2023-03-11 13:43 UTC, gabrielKerekes approved these changes

2023-03-11 13:45 UTC, merged