Add markdown support to lecture and post comments
StreetOfCode/streetofcode-web pull request #44
Opened 2023-03-20 22:12 UTC by gabrielKerekes

Coded on stream.

Could be made a bit nicer for sure, but IMO this is good enough for 
now.

I added a task to Trello for refactoring the whole comments stuff 
because there is a lot of duplication.

2023-03-20 22:15 UTC, gabrielKerekes commented on src/components/domain/lecture-comment/EditableLectureComment.tsx
> +  const containsMarkdown =
We can (and probably should) improve this later on.

2023-03-21 19:25 UTC, xjahic commented
The current implementation contains some bugs and needs improvement.
![Screenshot 2023-03-21 193812](https://user-images.githubusercontent.com/10036698/226717927-93ca105a-d96d-4e2b-92a2-784b5e86b567.png)
Bug 1. - If you submit in preview mode, the preview mode icon will stay in put. 
Bug 2. - The icon should not be shown if text is empty
Bug 3. - Weird scrollbar in comments. 

About improvements. 
- The icon should be accompanied by some text that could also signal user that using markdown is an option. 
- Some padding

You can see my idea of improvements in this 2 screenshots
![Screenshot 2023-03-21 195628](https://user-images.githubusercontent.com/10036698/226718916-33f1c291-f30e-4402-a719-83575489ddd9.png)

![Screenshot 2023-03-21 195645](https://user-images.githubusercontent.com/10036698/226718956-e42ae743-5d1f-4e33-ba8f-76963da333bf.png)
Code version - https://github.com/StreetOfCode/streetofcode-web/tree/jj/markdown-in-comments-v1

I have also tried using MDEditor to see if it was customizable and I think we could easily work with it if we wanted. We would set some good default values and remove few toolbar options and be good to go. Also screenshot.
![Screenshot 2023-03-21 201730](https://user-images.githubusercontent.com/10036698/226719199-da4f0ac2-e0d0-4580-94fd-6941848847d6.png)
Code version - https://github.com/StreetOfCode/streetofcode-web/tree/jj/makrdown-with-mdeditor

2023-03-21 19:26 UTC, xjahic requested changes
The current implementation contains some bugs and needs improvement.
![Screenshot 2023-03-21 193812](https://user-images.githubusercontent.com/10036698/226717927-93ca105a-d96d-4e2b-92a2-784b5e86b567.png)
Bug 1. - If you submit in preview mode, the preview mode icon will stay in put. 
Bug 2. - The icon should not be shown if text is empty
Bug 3. - Weird scrollbar in comments. 

About improvements. 
- The icon should be accompanied by some text that could also signal user that using markdown is an option. 
- Some padding

You can see my idea of improvements in this 2 screenshots
![Screenshot 2023-03-21 195628](https://user-images.githubusercontent.com/10036698/226718916-33f1c291-f30e-4402-a719-83575489ddd9.png)

![Screenshot 2023-03-21 195645](https://user-images.githubusercontent.com/10036698/226718956-e42ae743-5d1f-4e33-ba8f-76963da333bf.png)
Code version - https://github.com/StreetOfCode/streetofcode-web/tree/jj/markdown-in-comments-v1

I have also tried using MDEditor to see if it was customizable and I think we could easily work with it if we wanted. We would set some good default values and remove few toolbar options and be good to go. Also screenshot.
![Screenshot 2023-03-21 201730](https://user-images.githubusercontent.com/10036698/226719199-da4f0ac2-e0d0-4580-94fd-6941848847d6.png)
Code version - https://github.com/StreetOfCode/streetofcode-web/tree/jj/makrdown-with-mdeditor

2023-06-05 06:33 UTC, gabrielKerekes commented
I feel like md editor is a bit of an overkill. The comments should still be just comments and md-editor is a bit overwhelming for that. My assumption is that 95% of comments will not contain any markdown and so always showing md-editor isn't nice. I also wasn't able to quickly make it work with darkmode for example. For now, I'd leave this as it is in this PR. Also when editing a comment the window is just too narrow to be split in half. All of this can of course be addressed I just don't think it's worth it now.

The bugs and improvements you mentioned have been implemented in https://github.com/StreetOfCode/streetofcode-web/pull/44/commits/ed6b6ecd2135a968bfb9ffa6d81347d5a65db289.

2023-06-05 07:02 UTC, xjahic approved these changes
LGTM. Agree on unnecessary md-editor.

2023-06-07 08:55 UTC, merged