Add `videa` page (YouTube videos)
StreetOfCode/streetofcode-web pull request #46
Opened 2023-10-01 11:00 UTC by gabrielKerekes

Not much to say about FE. I'll leave comments on non-obvious lines in the code.

2023-10-01 11:09 UTC, gabrielKerekes commented on src/pages/videa/[slug].tsx
> +const videoDescriptionToHTML = (description: string) => {
Some magic to make the video descriptions appear similarly to YouTube.  I.e. URLs become clickable links and the description lines are nicely separated.

2023-10-02 09:59 UTC, xjahic requested changes
Otherwise LGTM. Search input would be nice as well.

2023-10-02 09:59 UTC, xjahic commented on src/components/domain/youtube/YouTubePreviewCard.tsx
> +/***
Edit comment pls

2023-10-02 09:59 UTC, xjahic commented on src/pages/videa/[slug].tsx
> +  const video = await (await fetch(youtubeVideoUrl(slug))).json()
Please add a logic to return notFound page if video with the specific slug doesn't exist. Now it just throws error

2023-10-02 09:59 UTC, xjahic commented on src/pages/videa/[slug].tsx
> +          <iframe
This is not responsive. Tags bellow are not applied.

2023-10-02 19:36 UTC, gabrielKerekes commented on src/components/domain/youtube/YouTubePreviewCard.tsx
> +/***
https://github.com/StreetOfCode/streetofcode-web/pull/46/commits/65e6668df19e0f8c02f973574dc71ae95ff3c38c

2023-10-02 19:37 UTC, gabrielKerekes commented on src/pages/videa/[slug].tsx
> +  const video = await (await fetch(youtubeVideoUrl(slug))).json()
https://github.com/StreetOfCode/streetofcode-web/pull/46/commits/65e6668df19e0f8c02f973574dc71ae95ff3c38c

2023-10-02 19:37 UTC, gabrielKerekes commented on src/pages/videa/[slug].tsx
> +          <iframe
moved the tags to a proper place. https://github.com/StreetOfCode/streetofcode-web/pull/46/commits/65e6668df19e0f8c02f973574dc71ae95ff3c38c

2023-10-03 06:53 UTC, xjahic approved these changes

2023-10-03 06:59 UTC, merged